# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        stages:
          - commit
          - manual
      - id: end-of-file-fixer
        stages:
          - commit
          - manual
      - id: check-yaml
        args: ["--unsafe"]
        stages:
          - commit
          - manual
      - id: check-added-large-files
        stages:
          - commit
          - manual
      - id: check-executables-have-shebangs
        stages:
          - commit
          - manual
      - id: check-json
        stages:
          - commit
          - manual
      - id: check-shebang-scripts-are-executable
        stages:
          - commit
          - manual
      - id: check-symlinks
        stages:
          - commit
          - manual
      - id: detect-private-key
        stages:
          - commit
          - manual
      - id: mixed-line-ending
        stages:
          - commit
          - manual
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.10.0
    hooks:
      - id: commitlint
        stages:
          - commit-msg
        additional_dependencies: ['@commitlint/config-conventional']
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-imports-repo
        stages:
          - commit
          - manual
        args: ["-w", "-d=false"]
        alias: go-imports
      - id: go-mod-tidy
        stages:
          - commit
          - manual
        alias: go-mod-tidy
      - id: go-vet-repo-mod
        stages:
          - commit
          - manual
        alias: go-vet
      - id: golangci-lint-repo-mod
        stages:
          - commit
          - manual
        alias: golangci-lint
      - id: go-test-repo-mod
        stages:
          - commit
          - manual
        verbose: true
        alias: go-test
      - id: go-test-repo-mod
        stages:
          - commit
          - manual
        args:
          - --race
          - --hook:env:CGO_ENABLED=1
        verbose: true
        alias: go-test-race
